#include "Kinai/Platform/Emscripten/Emscripten.hpp"
#include "Kinai/Core/Input.hpp"

namespace Kinai
{

#define EM_KEYCODE(_name, _key) if (!std::strcmp(e->code, _name)) { return _key; }

ImGuiKey	Em_KeyEventToImGuiKey(const EmscriptenKeyboardEvent* e)
{
	switch (e->keyCode)
	{
		// case DOM_VK_CANCEL: return ImGuiKey_;
		// case DOM_VK_HELP: return ImGuiKey_;
		case DOM_VK_BACK_SPACE: return ImGuiKey_Backspace;
		case DOM_VK_TAB: return ImGuiKey_Tab;
		// case DOM_VK_CLEAR: return ImGuiKey_;
		case DOM_VK_RETURN: return ImGuiKey_Enter;
		case DOM_VK_ENTER: return ImGuiKey_KeypadEnter;
		case DOM_VK_SHIFT: return e->location == 1 ? ImGuiKey_LeftShift : ImGuiKey_RightShift;
		case DOM_VK_CONTROL: return e->location == 1 ? ImGuiKey_LeftCtrl : ImGuiKey_RightCtrl;
		case DOM_VK_ALT: return e->location == 1 ? ImGuiKey_LeftAlt : ImGuiKey_RightAlt;
		case DOM_VK_PAUSE: return ImGuiKey_Pause;
		case DOM_VK_CAPS_LOCK: return ImGuiKey_CapsLock;
		// case DOM_VK_KANA: return ImGuiKey_;
		// case DOM_VK_HANGUL: return ImGuiKey_;
		// case DOM_VK_EISU: return ImGuiKey_;
		// case DOM_VK_JUNJA: return ImGuiKey_;
		// case DOM_VK_FINAL: return ImGuiKey_;
		// case DOM_VK_HANJA: return ImGuiKey_;
		// case DOM_VK_KANJI: return ImGuiKey_;
		case DOM_VK_ESCAPE: return ImGuiKey_Escape;
		// case DOM_VK_CONVERT: return ImGuiKey_;
		// case DOM_VK_NONCONVERT: return ImGuiKey_;
		// case DOM_VK_ACCEPT: return ImGuiKey_;
		// case DOM_VK_MODECHANGE: return ImGuiKey_;
		case DOM_VK_SPACE: return ImGuiKey_Space;
		case DOM_VK_PAGE_UP: return ImGuiKey_PageUp;
		case DOM_VK_PAGE_DOWN: return ImGuiKey_PageDown;
		case DOM_VK_END: return ImGuiKey_End;
		case DOM_VK_HOME: return ImGuiKey_Home;
		case DOM_VK_LEFT: return ImGuiKey_LeftArrow;
		case DOM_VK_UP: return ImGuiKey_UpArrow;
		case DOM_VK_RIGHT: return ImGuiKey_RightArrow;
		case DOM_VK_DOWN: return ImGuiKey_DownArrow;
		// case DOM_VK_SELECT: return ImGuiKey_;
		// case DOM_VK_PRINT: return ImGuiKey_;
		// case DOM_VK_EXECUTE: return ImGuiKey_;
		case DOM_VK_PRINTSCREEN: return ImGuiKey_PrintScreen;
		case DOM_VK_INSERT: return ImGuiKey_Insert;
		case DOM_VK_DELETE: return ImGuiKey_Delete;
		case DOM_VK_0: return ImGuiKey_0;
		case DOM_VK_1: return ImGuiKey_1;
		case DOM_VK_2: return ImGuiKey_2;
		case DOM_VK_3: return ImGuiKey_3;
		case DOM_VK_4: return ImGuiKey_4;
		case DOM_VK_5: return ImGuiKey_5;
		case DOM_VK_6: return ImGuiKey_6;
		case DOM_VK_7: return ImGuiKey_7;
		case DOM_VK_8: return ImGuiKey_8;
		case DOM_VK_9: return ImGuiKey_9;
		// case DOM_VK_COLON: return ImGuiKey_;
		case DOM_VK_SEMICOLON: return ImGuiKey_Semicolon;
		case DOM_VK_LESS_THAN: return ImGuiKey_LeftBracket;
		case DOM_VK_EQUALS: return ImGuiKey_Equal;
		case DOM_VK_GREATER_THAN: return ImGuiKey_RightBracket;
		// case DOM_VK_QUESTION_MARK: return ImGuiKey_;
		// case DOM_VK_AT: return ImGuiKey_;
		case DOM_VK_A: return ImGuiKey_A;
		case DOM_VK_B: return ImGuiKey_B;
		case DOM_VK_C: return ImGuiKey_C;
		case DOM_VK_D: return ImGuiKey_D;
		case DOM_VK_E: return ImGuiKey_E;
		case DOM_VK_F: return ImGuiKey_F;
		case DOM_VK_G: return ImGuiKey_G;
		case DOM_VK_H: return ImGuiKey_H;
		case DOM_VK_I: return ImGuiKey_I;
		case DOM_VK_J: return ImGuiKey_J;
		case DOM_VK_K: return ImGuiKey_K;
		case DOM_VK_L: return ImGuiKey_L;
		case DOM_VK_M: return ImGuiKey_M;
		case DOM_VK_N: return ImGuiKey_N;
		case DOM_VK_O: return ImGuiKey_O;
		case DOM_VK_P: return ImGuiKey_P;
		case DOM_VK_Q: return ImGuiKey_Q;
		case DOM_VK_R: return ImGuiKey_R;
		case DOM_VK_S: return ImGuiKey_S;
		case DOM_VK_T: return ImGuiKey_T;
		case DOM_VK_U: return ImGuiKey_U;
		case DOM_VK_V: return ImGuiKey_V;
		case DOM_VK_W: return ImGuiKey_W;
		case DOM_VK_X: return ImGuiKey_X;
		case DOM_VK_Y: return ImGuiKey_Y;
		case DOM_VK_Z: return ImGuiKey_Z;
		case DOM_VK_WIN: return e->location == 1 ? ImGuiKey_LeftSuper : ImGuiKey_RightSuper;
		case DOM_VK_CONTEXT_MENU: return ImGuiKey_Menu;
		// case DOM_VK_SLEEP: return ImGuiKey_;
		case DOM_VK_NUMPAD0: return ImGuiKey_Keypad0;
		case DOM_VK_NUMPAD1: return ImGuiKey_Keypad1;
		case DOM_VK_NUMPAD2: return ImGuiKey_Keypad2;
		case DOM_VK_NUMPAD3: return ImGuiKey_Keypad3;
		case DOM_VK_NUMPAD4: return ImGuiKey_Keypad4;
		case DOM_VK_NUMPAD5: return ImGuiKey_Keypad5;
		case DOM_VK_NUMPAD6: return ImGuiKey_Keypad6;
		case DOM_VK_NUMPAD7: return ImGuiKey_Keypad7;
		case DOM_VK_NUMPAD8: return ImGuiKey_Keypad8;
		case DOM_VK_NUMPAD9: return ImGuiKey_Keypad9;
		case DOM_VK_MULTIPLY: return ImGuiKey_KeypadMultiply;
		case DOM_VK_ADD: return ImGuiKey_KeypadAdd;
		// case DOM_VK_SEPARATOR: return ImGuiKey_;
		case DOM_VK_SUBTRACT: return ImGuiKey_KeypadSubtract;
		case DOM_VK_DECIMAL: return ImGuiKey_KeypadDecimal;
		case DOM_VK_DIVIDE: return ImGuiKey_KeypadDivide;
		case DOM_VK_F1: return ImGuiKey_F1;
		case DOM_VK_F2: return ImGuiKey_F2;
		case DOM_VK_F3: return ImGuiKey_F3;
		case DOM_VK_F4: return ImGuiKey_F4;
		case DOM_VK_F5: return ImGuiKey_F5;
		case DOM_VK_F6: return ImGuiKey_F6;
		case DOM_VK_F7: return ImGuiKey_F7;
		case DOM_VK_F8: return ImGuiKey_F8;
		case DOM_VK_F9: return ImGuiKey_F9;
		case DOM_VK_F10: return ImGuiKey_F10;
		case DOM_VK_F11: return ImGuiKey_F11;
		case DOM_VK_F12: return ImGuiKey_F12;
		case DOM_VK_F13: return ImGuiKey_F13;
		case DOM_VK_F14: return ImGuiKey_F14;
		case DOM_VK_F15: return ImGuiKey_F15;
		case DOM_VK_F16: return ImGuiKey_F16;
		case DOM_VK_F17: return ImGuiKey_F17;
		case DOM_VK_F18: return ImGuiKey_F18;
		case DOM_VK_F19: return ImGuiKey_F19;
		case DOM_VK_F20: return ImGuiKey_F20;
		case DOM_VK_F21: return ImGuiKey_F21;
		case DOM_VK_F22: return ImGuiKey_F22;
		case DOM_VK_F23: return ImGuiKey_F23;
		case DOM_VK_F24: return ImGuiKey_F24;
		case DOM_VK_NUM_LOCK: return ImGuiKey_NumLock;
		case DOM_VK_SCROLL_LOCK: return ImGuiKey_ScrollLock;
		// case DOM_VK_WIN_OEM_FJ_JISHO: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_FJ_MASSHOU: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_FJ_TOUROKU: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_FJ_LOYA: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_FJ_ROYA: return ImGuiKey_;
		// case DOM_VK_CIRCUMFLEX: return ImGuiKey_;
		// case DOM_VK_EXCLAMATION: return ImGuiKey_;
		// case DOM_VK_DOUBLE_QUOTE: return ImGuiKey_;
		// case DOM_VK_HASH: return ImGuiKey_;
		// case DOM_VK_DOLLAR: return ImGuiKey_;
		// case DOM_VK_PERCENT: return ImGuiKey_;
		// case DOM_VK_AMPERSAND: return ImGuiKey_;
		// case DOM_VK_UNDERSCORE: return ImGuiKey_;
		// case DOM_VK_OPEN_PAREN: return ImGuiKey_;
		// case DOM_VK_CLOSE_PAREN: return ImGuiKey_;
		case DOM_VK_ASTERISK: return ImGuiKey_KeypadMultiply;
		case DOM_VK_PLUS: return ImGuiKey_KeypadAdd;
		// case DOM_VK_PIPE: return ImGuiKey_;
		case DOM_VK_HYPHEN_MINUS: return ImGuiKey_Minus;
		case DOM_VK_OPEN_CURLY_BRACKET: return ImGuiKey_LeftBracket;
		case DOM_VK_CLOSE_CURLY_BRACKET: return ImGuiKey_RightBracket;
		// case DOM_VK_TILDE: return ImGuiKey_;
		// case DOM_VK_VOLUME_MUTE: return ImGuiKey_;
		// case DOM_VK_VOLUME_DOWN: return ImGuiKey_;
		// case DOM_VK_VOLUME_UP: return ImGuiKey_;
		case DOM_VK_COMMA: return ImGuiKey_Comma;
		case DOM_VK_PERIOD: return ImGuiKey_Period;
		case DOM_VK_SLASH: return ImGuiKey_Slash;
		// case DOM_VK_BACK_QUOTE: return ImGuiKey_;
		case DOM_VK_OPEN_BRACKET: return ImGuiKey_LeftBracket;
		case DOM_VK_BACK_SLASH: return ImGuiKey_Backslash;
		case DOM_VK_CLOSE_BRACKET: return ImGuiKey_RightBracket;
		// case DOM_VK_QUOTE: return ImGuiKey_;
		case DOM_VK_META: return e->location == 1 ? ImGuiKey_LeftSuper : ImGuiKey_RightSuper;
		case DOM_VK_ALTGR: return ImGuiKey_RightAlt;
		// case DOM_VK_WIN_ICO_HELP: return ImGuiKey_;
		// case DOM_VK_WIN_ICO_00: return ImGuiKey_;
		// case DOM_VK_WIN_ICO_CLEAR: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_RESET: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_JUMP: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_PA1: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_PA2: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_PA3: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_WSCTRL: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_CUSEL: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_ATTN: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_FINISH: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_COPY: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_AUTO: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_ENLW: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_BACKTAB: return ImGuiKey_;
		// case DOM_VK_ATTN: return ImGuiKey_;
		// case DOM_VK_CRSEL: return ImGuiKey_;
		// case DOM_VK_EXSEL: return ImGuiKey_;
		// case DOM_VK_EREOF: return ImGuiKey_;
		// case DOM_VK_PLAY: return ImGuiKey_;
		// case DOM_VK_ZOOM: return ImGuiKey_;
		// case DOM_VK_PA1: return ImGuiKey_;
		// case DOM_VK_WIN_OEM_CLEAR: return ImGuiKey_;
	}

	{
		EM_KEYCODE("Escape", ImGuiKey_Escape);
		EM_KEYCODE("Digit1", ImGuiKey_1);
		EM_KEYCODE("Digit2", ImGuiKey_2);
		EM_KEYCODE("Digit3", ImGuiKey_3);
		EM_KEYCODE("Digit4", ImGuiKey_4);
		EM_KEYCODE("Digit5", ImGuiKey_5);
		EM_KEYCODE("Digit6", ImGuiKey_6);
		EM_KEYCODE("Digit7", ImGuiKey_7);
		EM_KEYCODE("Digit8", ImGuiKey_8);
		EM_KEYCODE("Digit9", ImGuiKey_9);
		EM_KEYCODE("Digit0", ImGuiKey_0);
		EM_KEYCODE("Minus", ImGuiKey_Minus);
		EM_KEYCODE("Equal", ImGuiKey_Equal);
		EM_KEYCODE("Backspace", ImGuiKey_Backspace);
		EM_KEYCODE("Tab", ImGuiKey_Tab);
		EM_KEYCODE("KeyQ", ImGuiKey_Q);
		EM_KEYCODE("KeyW", ImGuiKey_W);
		EM_KEYCODE("KeyE", ImGuiKey_E);
		EM_KEYCODE("KeyR", ImGuiKey_R);
		EM_KEYCODE("KeyT", ImGuiKey_T);
		EM_KEYCODE("KeyY", ImGuiKey_Y);
		EM_KEYCODE("KeyU", ImGuiKey_U);
		EM_KEYCODE("KeyI", ImGuiKey_I);
		EM_KEYCODE("KeyO", ImGuiKey_O);
		EM_KEYCODE("KeyP", ImGuiKey_P);
		EM_KEYCODE("BracketLeft", ImGuiKey_LeftBracket);
		EM_KEYCODE("BracketRight", ImGuiKey_RightBracket);
		EM_KEYCODE("Enter", ImGuiKey_Enter);
		EM_KEYCODE("ControlLeft", ImGuiKey_LeftCtrl);
		EM_KEYCODE("KeyA", ImGuiKey_A);
		EM_KEYCODE("KeyS", ImGuiKey_S);
		EM_KEYCODE("KeyD", ImGuiKey_D);
		EM_KEYCODE("KeyF", ImGuiKey_F);
		EM_KEYCODE("KeyG", ImGuiKey_G);
		EM_KEYCODE("KeyH", ImGuiKey_H);
		EM_KEYCODE("KeyJ", ImGuiKey_J);
		EM_KEYCODE("KeyK", ImGuiKey_K);
		EM_KEYCODE("KeyL", ImGuiKey_L);
		EM_KEYCODE("Semicolon", ImGuiKey_Semicolon);
		// EM_KEYCODE("Quote", ImGuiKey_Quote);
		// EM_KEYCODE("Backquote", ImGuiKey_BackQuote);
		EM_KEYCODE("ShiftLeft", ImGuiKey_LeftShift);
		EM_KEYCODE("Backslash", ImGuiKey_Backslash);
		EM_KEYCODE("KeyZ", ImGuiKey_Z);
		EM_KEYCODE("KeyX", ImGuiKey_X);
		EM_KEYCODE("KeyC", ImGuiKey_C);
		EM_KEYCODE("KeyV", ImGuiKey_V);
		EM_KEYCODE("KeyB", ImGuiKey_B);
		EM_KEYCODE("KeyN", ImGuiKey_N);
		EM_KEYCODE("KeyM", ImGuiKey_M);
		EM_KEYCODE("Comma", ImGuiKey_Comma);
		EM_KEYCODE("Period", ImGuiKey_Period);
		EM_KEYCODE("Slash", ImGuiKey_Slash);
		EM_KEYCODE("ShiftRight", ImGuiKey_RightShift);
		EM_KEYCODE("NumpadMultiply", ImGuiKey_KeypadMultiply);
		EM_KEYCODE("AltLeft", ImGuiKey_LeftAlt);
		EM_KEYCODE("Space", ImGuiKey_Space);
		EM_KEYCODE("CapsLock", ImGuiKey_CapsLock);
		EM_KEYCODE("F1", ImGuiKey_F1);
		EM_KEYCODE("F2", ImGuiKey_F2);
		EM_KEYCODE("F3", ImGuiKey_F3);
		EM_KEYCODE("F4", ImGuiKey_F4);
		EM_KEYCODE("F5", ImGuiKey_F5);
		EM_KEYCODE("F6", ImGuiKey_F6);
		EM_KEYCODE("F7", ImGuiKey_F7);
		EM_KEYCODE("F8", ImGuiKey_F8);
		EM_KEYCODE("F9", ImGuiKey_F9);
		EM_KEYCODE("F10", ImGuiKey_F10);
		EM_KEYCODE("F11", ImGuiKey_F11);
		EM_KEYCODE("F12", ImGuiKey_F12);
		EM_KEYCODE("F13", ImGuiKey_F13);
		EM_KEYCODE("F14", ImGuiKey_F14);
		EM_KEYCODE("F15", ImGuiKey_F15);
		EM_KEYCODE("F16", ImGuiKey_F16);
		EM_KEYCODE("F17", ImGuiKey_F17);
		EM_KEYCODE("F18", ImGuiKey_F18);
		EM_KEYCODE("F19", ImGuiKey_F19);
		EM_KEYCODE("F20", ImGuiKey_F20);
		EM_KEYCODE("F21", ImGuiKey_F21);
		EM_KEYCODE("F22", ImGuiKey_F22);
		EM_KEYCODE("F23", ImGuiKey_F23);
		EM_KEYCODE("F24", ImGuiKey_F24);
		EM_KEYCODE("Pause", ImGuiKey_Pause);
		EM_KEYCODE("ScrollLock", ImGuiKey_ScrollLock);
		EM_KEYCODE("Numpad7", ImGuiKey_Keypad7);
		EM_KEYCODE("Numpad8", ImGuiKey_Keypad8);
		EM_KEYCODE("Numpad9", ImGuiKey_Keypad9);
		EM_KEYCODE("NumpadSubtract", ImGuiKey_KeypadSubtract);
		EM_KEYCODE("Numpad4", ImGuiKey_Keypad4);
		EM_KEYCODE("Numpad5", ImGuiKey_Keypad5);
		EM_KEYCODE("Numpad6", ImGuiKey_Keypad6);
		EM_KEYCODE("NumpadAdd", ImGuiKey_KeypadAdd);
		EM_KEYCODE("Numpad1", ImGuiKey_Keypad1);
		EM_KEYCODE("Numpad2", ImGuiKey_Keypad2);
		EM_KEYCODE("Numpad3", ImGuiKey_Keypad3);
		EM_KEYCODE("Numpad0", ImGuiKey_Keypad0);
		EM_KEYCODE("NumpadDecimal", ImGuiKey_KeypadDecimal);
		EM_KEYCODE("PrintScreen", ImGuiKey_PrintScreen);
		// EM_KEYCODE("IntlBackslash", ImGuiKey_IntlBackslash);
		EM_KEYCODE("NumpadEqual", ImGuiKey_KeypadEqual);
		// EM_KEYCODE("KanaMode", ImGuiKey_KanaMode);
		// EM_KEYCODE("Lang2", ImGuiKey_Lang2);
		// EM_KEYCODE("Lang1", ImGuiKey_Lang1);
		// EM_KEYCODE("IntlRo", ImGuiKey_IntlRo);
		// EM_KEYCODE("Lang4", ImGuiKey_Lang4);
		// EM_KEYCODE("Lang3", ImGuiKey_Lang3);
		// EM_KEYCODE("Convert", ImGuiKey_Convert);
		// EM_KEYCODE("NonConvert", ImGuiKey_NonConvert);
		// EM_KEYCODE("IntlYen", ImGuiKey_IntlYen);
		EM_KEYCODE("NumpadComma", ImGuiKey_KeypadDecimal);
		// EM_KEYCODE("Undo", ImGuiKey_Undo);
		// EM_KEYCODE("Paste", ImGuiKey_Paste);
		// EM_KEYCODE("MediaTrackPrevious", ImGuiKey_MediaTrackPrevious);
		// EM_KEYCODE("Cut", ImGuiKey_Cut);
		// EM_KEYCODE("Copy", ImGuiKey_Copy);
		// EM_KEYCODE("MediaTrackNext", ImGuiKey_MediaTrackNext);
		EM_KEYCODE("NumpadEnter", ImGuiKey_KeypadEnter);
		EM_KEYCODE("ControlRight", ImGuiKey_RightCtrl);
		// EM_KEYCODE("AudioVolumeMute", ImGuiKey_AudioVolumeMute);
		// EM_KEYCODE("LaunchApp2", ImGuiKey_LaunchApp2);
		// EM_KEYCODE("MediaPlayPause", ImGuiKey_MediaPlayPause);
		// EM_KEYCODE("MediaStop", ImGuiKey_MediaStop);
		// EM_KEYCODE("Eject", ImGuiKey_Eject);
		// EM_KEYCODE("AudioVolumeDown", ImGuiKey_AudioVolumeDown);
		// EM_KEYCODE("AudioVolumeUp", ImGuiKey_AudioVolumeUp);
		// EM_KEYCODE("BrowserHome", ImGuiKey_BrowserHome);
		EM_KEYCODE("NumpadDivide", ImGuiKey_KeypadDivide);
		EM_KEYCODE("PrintScreen", ImGuiKey_PrintScreen);
		EM_KEYCODE("AltRight", ImGuiKey_RightAlt);
		// EM_KEYCODE("Help", ImGuiKey_Help);
		EM_KEYCODE("NumLock", ImGuiKey_NumLock);
		EM_KEYCODE("Pause", ImGuiKey_Pause);
		EM_KEYCODE("Home", ImGuiKey_Home);
		EM_KEYCODE("ArrowUp", ImGuiKey_UpArrow);
		EM_KEYCODE("PageUp", ImGuiKey_PageUp);
		EM_KEYCODE("ArrowLeft", ImGuiKey_LeftArrow);
		EM_KEYCODE("ArrowRight", ImGuiKey_RightArrow);
		EM_KEYCODE("End", ImGuiKey_End);
		EM_KEYCODE("ArrowDown", ImGuiKey_DownArrow);
		EM_KEYCODE("PageDown", ImGuiKey_PageDown);
		EM_KEYCODE("Insert", ImGuiKey_Insert);
		EM_KEYCODE("Delete", ImGuiKey_Delete);
		EM_KEYCODE("MetaLeft", ImGuiKey_LeftSuper);
		EM_KEYCODE("MetaRight", ImGuiKey_RightSuper);
		EM_KEYCODE("ContextMenu", ImGuiKey_Menu);
		// EM_KEYCODE("Power", ImGuiKey_Power);
		// EM_KEYCODE("Sleep", ImGuiKey_Sleep);
		// EM_KEYCODE("WakeUp", ImGuiKey_WakeUp);
		// EM_KEYCODE("BrowserSearch", ImGuiKey_BrowserSearch);
		// EM_KEYCODE("BrowserFavorites", ImGuiKey_BrowserFavorites);
		// EM_KEYCODE("BrowserRefresh", ImGuiKey_BrowserRefresh);
		// EM_KEYCODE("BrowserStop", ImGuiKey_BrowserStop);
		EM_KEYCODE("BrowserForward", ImGuiKey_AppForward);
		EM_KEYCODE("BrowserBack", ImGuiKey_AppBack);
		// EM_KEYCODE("LaunchApp1", ImGuiKey_LaunchApp1);
		// EM_KEYCODE("LaunchMail", ImGuiKey_LaunchMail);
		// EM_KEYCODE("MediaSelect", ImGuiKey_MediaSelect);
	}
	return ImGuiKey_None;
}

KeyCode	Em_KeyEventToKeyCode(const EmscriptenKeyboardEvent* e)
{
	// switch (e->keyCode)
	// {
	// 	// case DOM_VK_CANCEL: return Key::;
	// 	// case DOM_VK_HELP: return Key::;
	// 	case DOM_VK_BACK_SPACE: return Key::Backspace;
	// 	case DOM_VK_TAB: return Key::Tab;
	// 	// case DOM_VK_CLEAR: return Key::;
	// 	case DOM_VK_RETURN: return Key::Return;
	// 	case DOM_VK_ENTER: return Key::KPEnter;
	// 	case DOM_VK_SHIFT: return e->location == 1 ? Key::LeftShift : Key::RightShift;
	// 	case DOM_VK_CONTROL: return e->location == 1 ? Key::LeftCtrl : Key::RightCtrl;
	// 	case DOM_VK_ALT: return e->location == 1 ? Key::LeftAlt : Key::RightAlt;
	// 	case DOM_VK_PAUSE: return Key::Pause;
	// 	case DOM_VK_CAPS_LOCK: return Key::CapsLock;
	// 	// case DOM_VK_KANA: return Key::;
	// 	// case DOM_VK_HANGUL: return Key::;
	// 	// case DOM_VK_EISU: return Key::;
	// 	// case DOM_VK_JUNJA: return Key::;
	// 	// case DOM_VK_FINAL: return Key::;
	// 	// case DOM_VK_HANJA: return Key::;
	// 	// case DOM_VK_KANJI: return Key::;
	// 	case DOM_VK_ESCAPE: return Key::Escape;
	// 	// case DOM_VK_CONVERT: return Key::;
	// 	// case DOM_VK_NONCONVERT: return Key::;
	// 	// case DOM_VK_ACCEPT: return Key::;
	// 	// case DOM_VK_MODECHANGE: return Key::;
	// 	case DOM_VK_SPACE: return Key::Space;
	// 	case DOM_VK_PAGE_UP: return Key::PageUp;
	// 	case DOM_VK_PAGE_DOWN: return Key::PageDown;
	// 	case DOM_VK_END: return Key::End;
	// 	case DOM_VK_HOME: return Key::Home;
	// 	case DOM_VK_LEFT: return Key::Left;
	// 	case DOM_VK_UP: return Key::Up;
	// 	case DOM_VK_RIGHT: return Key::Right;
	// 	case DOM_VK_DOWN: return Key::Down;
	// 	// case DOM_VK_SELECT: return Key::;
	// 	// case DOM_VK_PRINT: return Key::;
	// 	// case DOM_VK_EXECUTE: return Key::;
	// 	case DOM_VK_PRINTSCREEN: return Key::PrintScreen;
	// 	case DOM_VK_INSERT: return Key::Insert;
	// 	case DOM_VK_DELETE: return Key::Delete;
	// 	case DOM_VK_0: return Key::D0;
	// 	case DOM_VK_1: return Key::D1;
	// 	case DOM_VK_2: return Key::D2;
	// 	case DOM_VK_3: return Key::D3;
	// 	case DOM_VK_4: return Key::D4;
	// 	case DOM_VK_5: return Key::D5;
	// 	case DOM_VK_6: return Key::D6;
	// 	case DOM_VK_7: return Key::D7;
	// 	case DOM_VK_8: return Key::D8;
	// 	case DOM_VK_9: return Key::D9;
	// 	// case DOM_VK_COLON: return Key::;
	// 	case DOM_VK_SEMICOLON: return Key::Semicolon;
	// 	case DOM_VK_LESS_THAN: return Key::LeftBracket;
	// 	case DOM_VK_EQUALS: return Key::Equals;
	// 	case DOM_VK_GREATER_THAN: return Key::RightBracket;
	// 	// case DOM_VK_QUESTION_MARK: return Key::;
	// 	// case DOM_VK_AT: return Key::;
	// 	case DOM_VK_A: return Key::A;
	// 	case DOM_VK_B: return Key::B;
	// 	case DOM_VK_C: return Key::C;
	// 	case DOM_VK_D: return Key::D;
	// 	case DOM_VK_E: return Key::E;
	// 	case DOM_VK_F: return Key::F;
	// 	case DOM_VK_G: return Key::G;
	// 	case DOM_VK_H: return Key::H;
	// 	case DOM_VK_I: return Key::I;
	// 	case DOM_VK_J: return Key::J;
	// 	case DOM_VK_K: return Key::K;
	// 	case DOM_VK_L: return Key::L;
	// 	case DOM_VK_M: return Key::M;
	// 	case DOM_VK_N: return Key::N;
	// 	case DOM_VK_O: return Key::O;
	// 	case DOM_VK_P: return Key::P;
	// 	case DOM_VK_Q: return Key::Q;
	// 	case DOM_VK_R: return Key::R;
	// 	case DOM_VK_S: return Key::S;
	// 	case DOM_VK_T: return Key::T;
	// 	case DOM_VK_U: return Key::U;
	// 	case DOM_VK_V: return Key::V;
	// 	case DOM_VK_W: return Key::W;
	// 	case DOM_VK_X: return Key::X;
	// 	case DOM_VK_Y: return Key::Y;
	// 	case DOM_VK_Z: return Key::Z;
	// 	case DOM_VK_WIN: return e->location == 1 ? Key::LeftSuper : Key::RightSuper;
	// 	case DOM_VK_CONTEXT_MENU: return Key::Menu;
	// 	// case DOM_VK_SLEEP: return Key::;
	// 	case DOM_VK_NUMPAD0: return Key::KP0;
	// 	case DOM_VK_NUMPAD1: return Key::KP1;
	// 	case DOM_VK_NUMPAD2: return Key::KP2;
	// 	case DOM_VK_NUMPAD3: return Key::KP3;
	// 	case DOM_VK_NUMPAD4: return Key::KP4;
	// 	case DOM_VK_NUMPAD5: return Key::KP5;
	// 	case DOM_VK_NUMPAD6: return Key::KP6;
	// 	case DOM_VK_NUMPAD7: return Key::KP7;
	// 	case DOM_VK_NUMPAD8: return Key::KP8;
	// 	case DOM_VK_NUMPAD9: return Key::KP9;
	// 	case DOM_VK_MULTIPLY: return Key::KPMultiply;
	// 	case DOM_VK_ADD: return Key::KPAdd;
	// 	// case DOM_VK_SEPARATOR: return Key::;
	// 	case DOM_VK_SUBTRACT: return Key::KPSubtract;
	// 	case DOM_VK_DECIMAL: return Key::KPPeriod;
	// 	case DOM_VK_DIVIDE: return Key::KPDivide;
	// 	case DOM_VK_F1: return Key::F1;
	// 	case DOM_VK_F2: return Key::F2;
	// 	case DOM_VK_F3: return Key::F3;
	// 	case DOM_VK_F4: return Key::F4;
	// 	case DOM_VK_F5: return Key::F5;
	// 	case DOM_VK_F6: return Key::F6;
	// 	case DOM_VK_F7: return Key::F7;
	// 	case DOM_VK_F8: return Key::F8;
	// 	case DOM_VK_F9: return Key::F9;
	// 	case DOM_VK_F10: return Key::F10;
	// 	case DOM_VK_F11: return Key::F11;
	// 	case DOM_VK_F12: return Key::F12;
	// 	case DOM_VK_F13: return Key::F13;
	// 	case DOM_VK_F14: return Key::F14;
	// 	case DOM_VK_F15: return Key::F15;
	// 	case DOM_VK_F16: return Key::F16;
	// 	case DOM_VK_F17: return Key::F17;
	// 	case DOM_VK_F18: return Key::F18;
	// 	case DOM_VK_F19: return Key::F19;
	// 	case DOM_VK_F20: return Key::F20;
	// 	case DOM_VK_F21: return Key::F21;
	// 	case DOM_VK_F22: return Key::F22;
	// 	case DOM_VK_F23: return Key::F23;
	// 	case DOM_VK_F24: return Key::F24;
	// 	case DOM_VK_NUM_LOCK: return Key::NumLockClear;
	// 	case DOM_VK_SCROLL_LOCK: return Key::ScrollLock;
	// 	// case DOM_VK_WIN_OEM_FJ_JISHO: return Key::;
	// 	// case DOM_VK_WIN_OEM_FJ_MASSHOU: return Key::;
	// 	// case DOM_VK_WIN_OEM_FJ_TOUROKU: return Key::;
	// 	// case DOM_VK_WIN_OEM_FJ_LOYA: return Key::;
	// 	// case DOM_VK_WIN_OEM_FJ_ROYA: return Key::;
	// 	// case DOM_VK_CIRCUMFLEX: return Key::;
	// 	// case DOM_VK_EXCLAMATION: return Key::;
	// 	// case DOM_VK_DOUBLE_QUOTE: return Key::;
	// 	// case DOM_VK_HASH: return Key::;
	// 	// case DOM_VK_DOLLAR: return Key::;
	// 	// case DOM_VK_PERCENT: return Key::;
	// 	// case DOM_VK_AMPERSAND: return Key::;
	// 	// case DOM_VK_UNDERSCORE: return Key::;
	// 	// case DOM_VK_OPEN_PAREN: return Key::;
	// 	// case DOM_VK_CLOSE_PAREN: return Key::;
	// 	case DOM_VK_ASTERISK: return Key::KPMultiply;
	// 	case DOM_VK_PLUS: return Key::KPAdd;
	// 	// case DOM_VK_PIPE: return Key::;
	// 	case DOM_VK_HYPHEN_MINUS: return Key::Minus;
	// 	case DOM_VK_OPEN_CURLY_BRACKET: return Key::LeftBracket;
	// 	case DOM_VK_CLOSE_CURLY_BRACKET: return Key::RightBracket;
	// 	// case DOM_VK_TILDE: return Key::;
	// 	// case DOM_VK_VOLUME_MUTE: return Key::;
	// 	// case DOM_VK_VOLUME_DOWN: return Key::;
	// 	// case DOM_VK_VOLUME_UP: return Key::;
	// 	case DOM_VK_COMMA: return Key::Comma;
	// 	case DOM_VK_PERIOD: return Key::Period;
	// 	case DOM_VK_SLASH: return Key::Slash;
	// 	// case DOM_VK_BACK_QUOTE: return Key::;
	// 	case DOM_VK_OPEN_BRACKET: return Key::LeftBracket;
	// 	case DOM_VK_BACK_SLASH: return Key::Backslash;
	// 	case DOM_VK_CLOSE_BRACKET: return Key::RightBracket;
	// 	// case DOM_VK_QUOTE: return Key::;
	// 	case DOM_VK_META: return e->location == 1 ? Key::LeftSuper : Key::RightSuper;
	// 	case DOM_VK_ALTGR: return Key::RightAlt;
	// 	// case DOM_VK_WIN_ICO_HELP: return Key::;
	// 	// case DOM_VK_WIN_ICO_00: return Key::;
	// 	// case DOM_VK_WIN_ICO_CLEAR: return Key::;
	// 	// case DOM_VK_WIN_OEM_RESET: return Key::;
	// 	// case DOM_VK_WIN_OEM_JUMP: return Key::;
	// 	// case DOM_VK_WIN_OEM_PA1: return Key::;
	// 	// case DOM_VK_WIN_OEM_PA2: return Key::;
	// 	// case DOM_VK_WIN_OEM_PA3: return Key::;
	// 	// case DOM_VK_WIN_OEM_WSCTRL: return Key::;
	// 	// case DOM_VK_WIN_OEM_CUSEL: return Key::;
	// 	// case DOM_VK_WIN_OEM_ATTN: return Key::;
	// 	// case DOM_VK_WIN_OEM_FINISH: return Key::;
	// 	// case DOM_VK_WIN_OEM_COPY: return Key::;
	// 	// case DOM_VK_WIN_OEM_AUTO: return Key::;
	// 	// case DOM_VK_WIN_OEM_ENLW: return Key::;
	// 	// case DOM_VK_WIN_OEM_BACKTAB: return Key::;
	// 	// case DOM_VK_ATTN: return Key::;
	// 	// case DOM_VK_CRSEL: return Key::;
	// 	// case DOM_VK_EXSEL: return Key::;
	// 	// case DOM_VK_EREOF: return Key::;
	// 	// case DOM_VK_PLAY: return Key::;
	// 	// case DOM_VK_ZOOM: return Key::;
	// 	// case DOM_VK_PA1: return Key::;
	// 	// case DOM_VK_WIN_OEM_CLEAR: return Key::;
	// }

	EM_KEYCODE("Escape", Key::Escape);
	EM_KEYCODE("Digit1", Key::D1);
	EM_KEYCODE("Digit2", Key::D2);
	EM_KEYCODE("Digit3", Key::D3);
	EM_KEYCODE("Digit4", Key::D4);
	EM_KEYCODE("Digit5", Key::D5);
	EM_KEYCODE("Digit6", Key::D6);
	EM_KEYCODE("Digit7", Key::D7);
	EM_KEYCODE("Digit8", Key::D8);
	EM_KEYCODE("Digit9", Key::D9);
	EM_KEYCODE("Digit0", Key::D0);
	EM_KEYCODE("Minus", Key::Minus);
	EM_KEYCODE("Equal", Key::Equals);
	EM_KEYCODE("Backspace", Key::Backspace);
	EM_KEYCODE("Tab", Key::Tab);
	EM_KEYCODE("KeyQ", Key::Q);
	EM_KEYCODE("KeyW", Key::W);
	EM_KEYCODE("KeyE", Key::E);
	EM_KEYCODE("KeyR", Key::R);
	EM_KEYCODE("KeyT", Key::T);
	EM_KEYCODE("KeyY", Key::Y);
	EM_KEYCODE("KeyU", Key::U);
	EM_KEYCODE("KeyI", Key::I);
	EM_KEYCODE("KeyO", Key::O);
	EM_KEYCODE("KeyP", Key::P);
	EM_KEYCODE("BracketLeft", Key::LeftBracket);
	EM_KEYCODE("BracketRight", Key::RightBracket);
	EM_KEYCODE("Enter", Key::Return);
	EM_KEYCODE("ControlLeft", Key::LeftCtrl);
	EM_KEYCODE("KeyA", Key::A);
	EM_KEYCODE("KeyS", Key::S);
	EM_KEYCODE("KeyD", Key::D);
	EM_KEYCODE("KeyF", Key::F);
	EM_KEYCODE("KeyG", Key::G);
	EM_KEYCODE("KeyH", Key::H);
	EM_KEYCODE("KeyJ", Key::J);
	EM_KEYCODE("KeyK", Key::K);
	EM_KEYCODE("KeyL", Key::L);
	EM_KEYCODE("Semicolon", Key::Semicolon);
	// EM_KEYCODE("Quote", Key::Quote);
	// EM_KEYCODE("Backquote", Key::BackQuote);
	EM_KEYCODE("ShiftLeft", Key::LeftShift);
	EM_KEYCODE("Backslash", Key::Backslash);
	EM_KEYCODE("KeyZ", Key::Z);
	EM_KEYCODE("KeyX", Key::X);
	EM_KEYCODE("KeyC", Key::C);
	EM_KEYCODE("KeyV", Key::V);
	EM_KEYCODE("KeyB", Key::B);
	EM_KEYCODE("KeyN", Key::N);
	EM_KEYCODE("KeyM", Key::M);
	EM_KEYCODE("Comma", Key::Comma);
	EM_KEYCODE("Period", Key::Period);
	EM_KEYCODE("Slash", Key::Slash);
	EM_KEYCODE("ShiftRight", Key::RightShift);
	EM_KEYCODE("NumpadMultiply", Key::KPMultiply);
	EM_KEYCODE("AltLeft", Key::LeftAlt);
	EM_KEYCODE("Space", Key::Space);
	EM_KEYCODE("CapsLock", Key::CapsLock);
	EM_KEYCODE("F1", Key::F1);
	EM_KEYCODE("F2", Key::F2);
	EM_KEYCODE("F3", Key::F3);
	EM_KEYCODE("F4", Key::F4);
	EM_KEYCODE("F5", Key::F5);
	EM_KEYCODE("F6", Key::F6);
	EM_KEYCODE("F7", Key::F7);
	EM_KEYCODE("F8", Key::F8);
	EM_KEYCODE("F9", Key::F9);
	EM_KEYCODE("F10", Key::F10);
	EM_KEYCODE("F11", Key::F11);
	EM_KEYCODE("F12", Key::F12);
	EM_KEYCODE("F13", Key::F13);
	EM_KEYCODE("F14", Key::F14);
	EM_KEYCODE("F15", Key::F15);
	EM_KEYCODE("F16", Key::F16);
	EM_KEYCODE("F17", Key::F17);
	EM_KEYCODE("F18", Key::F18);
	EM_KEYCODE("F19", Key::F19);
	EM_KEYCODE("F20", Key::F20);
	EM_KEYCODE("F21", Key::F21);
	EM_KEYCODE("F22", Key::F22);
	EM_KEYCODE("F23", Key::F23);
	EM_KEYCODE("F24", Key::F24);
	EM_KEYCODE("Pause", Key::Pause);
	EM_KEYCODE("ScrollLock", Key::ScrollLock);
	EM_KEYCODE("Numpad7", Key::KP7);
	EM_KEYCODE("Numpad8", Key::KP8);
	EM_KEYCODE("Numpad9", Key::KP9);
	EM_KEYCODE("NumpadSubtract", Key::KPSubtract);
	EM_KEYCODE("Numpad4", Key::KP4);
	EM_KEYCODE("Numpad5", Key::KP5);
	EM_KEYCODE("Numpad6", Key::KP6);
	EM_KEYCODE("NumpadAdd", Key::KPAdd);
	EM_KEYCODE("Numpad1", Key::KP1);
	EM_KEYCODE("Numpad2", Key::KP2);
	EM_KEYCODE("Numpad3", Key::KP3);
	EM_KEYCODE("Numpad0", Key::KP0);
	EM_KEYCODE("NumpadDecimal", Key::KPPeriod);
	EM_KEYCODE("PrintScreen", Key::PrintScreen);
	// EM_KEYCODE("IntlBackslash", Key::IntlBackslash);
	EM_KEYCODE("NumpadEqual", Key::KPEquals);
	// EM_KEYCODE("KanaMode", Key::KanaMode);
	// EM_KEYCODE("Lang2", Key::Lang2);
	// EM_KEYCODE("Lang1", Key::Lang1);
	// EM_KEYCODE("IntlRo", Key::IntlRo);
	// EM_KEYCODE("Lang4", Key::Lang4);
	// EM_KEYCODE("Lang3", Key::Lang3);
	// EM_KEYCODE("Convert", Key::Convert);
	// EM_KEYCODE("NonConvert", Key::NonConvert);
	// EM_KEYCODE("IntlYen", Key::IntlYen);
	EM_KEYCODE("NumpadComma", Key::KPPeriod);
	// EM_KEYCODE("Undo", Key::Undo);
	// EM_KEYCODE("Paste", Key::Paste);
	// EM_KEYCODE("MediaTrackPrevious", Key::MediaTrackPrevious);
	// EM_KEYCODE("Cut", Key::Cut);
	// EM_KEYCODE("Copy", Key::Copy);
	// EM_KEYCODE("MediaTrackNext", Key::MediaTrackNext);
	EM_KEYCODE("NumpadEnter", Key::KPEnter);
	EM_KEYCODE("ControlRight", Key::RightCtrl);
	// EM_KEYCODE("AudioVolumeMute", Key::AudioVolumeMute);
	// EM_KEYCODE("LaunchApp2", Key::LaunchApp2);
	// EM_KEYCODE("MediaPlayPause", Key::MediaPlayPause);
	// EM_KEYCODE("MediaStop", Key::MediaStop);
	// EM_KEYCODE("Eject", Key::Eject);
	// EM_KEYCODE("AudioVolumeDown", Key::AudioVolumeDown);
	// EM_KEYCODE("AudioVolumeUp", Key::AudioVolumeUp);
	// EM_KEYCODE("BrowserHome", Key::BrowserHome);
	EM_KEYCODE("NumpadDivide", Key::KPDivide);
	EM_KEYCODE("PrintScreen", Key::PrintScreen);
	EM_KEYCODE("AltRight", Key::RightAlt);
	// EM_KEYCODE("Help", Key::Help);
	EM_KEYCODE("NumLock", Key::NumLockClear);
	EM_KEYCODE("Pause", Key::Pause);
	EM_KEYCODE("Home", Key::Home);
	EM_KEYCODE("ArrowUp", Key::Up);
	EM_KEYCODE("PageUp", Key::PageUp);
	EM_KEYCODE("ArrowLeft", Key::Left);
	EM_KEYCODE("ArrowRight", Key::Right);
	EM_KEYCODE("End", Key::End);
	EM_KEYCODE("ArrowDown", Key::Down);
	EM_KEYCODE("PageDown", Key::PageDown);
	EM_KEYCODE("Insert", Key::Insert);
	EM_KEYCODE("Delete", Key::Delete);
	EM_KEYCODE("MetaLeft", Key::LeftSuper);
	EM_KEYCODE("MetaRight", Key::RightSuper);
	EM_KEYCODE("ContextMenu", Key::Menu);
	// EM_KEYCODE("Power", Key::Power);
	// EM_KEYCODE("Sleep", Key::Sleep);
	// EM_KEYCODE("WakeUp", Key::WakeUp);
	// EM_KEYCODE("BrowserSearch", Key::BrowserSearch);
	// EM_KEYCODE("BrowserFavorites", Key::BrowserFavorites);
	// EM_KEYCODE("BrowserRefresh", Key::BrowserRefresh);
	// EM_KEYCODE("BrowserStop", Key::BrowserStop);
	// EM_KEYCODE("BrowserForward", Key::AppForward);
	// EM_KEYCODE("BrowserBack", Key::AppBack);
	// EM_KEYCODE("LaunchApp1", Key::LaunchApp1);
	// EM_KEYCODE("LaunchMail", Key::LaunchMail);
	// EM_KEYCODE("MediaSelect", Key::MediaSelect);

	return Key::None;
}

bool	Input::IsKeyPressed(KeyCode key)
{
	return EmWindow::IsKeyPressed(key);
}

bool	Input::IsMouseButtonPressed(MouseButton button)
{
	return EmWindow::IsMouseButtonPressed(button);
}

glm::vec2	Input::GetMousePosition()
{
	float xpos, ypos;

	SDL_GetMouseState(&xpos, &ypos);
	return glm::vec2(xpos, ypos);
}

float	Input::GetMouseX()
{
	return GetMousePosition().x;
}

float	Input::GetMouseY()
{
	return GetMousePosition().y;
}

} // Kinai
