#include "shdc.h"

void	write_preprocessor(void)
{
	write_line("#pragma once\n");
	write_line("/*");
	write_line("\tGenerated by shdc\n");
	write_line("\tOverview:");
	write_line("\t=========");
	write_line("\tShader program: '%s':", shdc.program.name);
	write_line("\tGet shader config: %sProgramShaderConfig()", shdc.program.name);
	write_line("\t\tVertex Shader: %s", shdc.program.vs);
	write_line("\t\tFragment Shader: %s", shdc.program.fs);
	write_line("*/");
	write_line("#if !defined(KINAI_SHDC_ALIGN)");
	write_line("#if defined(_MSC_VER)");
	write_line("# define KINAI_SHDC_ALIGN(a) __declspec(align(a))");
	write_line("#else");
	write_line("# define KINAI_SHDC_ALIGN(a) __attribute__((aligned(a)))");
	write_line("#endif");
	write_line("#endif");
}
